In [1]:
#General
import numpy as np
import pandas as pd

#Data Retrieval and Visualization
import pandas_datareader.data as web
import datetime
import matplotlib.pyplot as plt
%matplotlib inline

#Statistical Package
from scipy import stats 
import statsmodels.api as sm
import math
from scipy.stats import linregress
from scipy.stats import f

/opt/anaconda3/lib/python3.7/site-packages/pandas_datareader/compat/__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

In [2]:
def fm_summary(p): #Summary Statistics Function
    s = p.describe().T
    s['std_error'] = s['std']/np.sqrt(s['count'])
    s['tstat'] = s['mean']/s['std_error']
    return s[['mean','std','tstat']].T
def update_withrf(dataport):
    for x in range(len(dataport.columns)):
        dataport.iloc[:,x]=dataport.iloc[:,x]-dataport['RF']
    dataport.drop('RF',axis=1,inplace=True)

In [38]:
vix=pd.read_csv('vixcurrent.csv')

In [39]:
vix.columns=['Date','Open','High','Low','Close']
vix=vix.drop([0])
vix=vix.set_index(['Date'])

In [40]:
vix.to_excel('VIXSpotDaily.xlsx')

In [43]:
df2=pd.read_excel("Term Structure of VIX-2.xlsx","REG1")

In [52]:
df2=df2.set_index(['Dates'])
df2

,UX1 Index,UX2 Index,UX3 Index,UX4 Index,UX5 Index,UX6 Index,UX7 Index,UX8 Index
Dates,,,,,,,,
2018-01-01,11.475,12.475,13.225,13.875,14.375,14.825,15.425,15.800
2018-01-02,10.875,11.975,12.825,13.525,14.025,14.525,15.125,15.575
2018-01-03,10.675,11.825,12.625,13.325,13.825,14.325,14.925,15.350
2018-01-04,10.575,11.825,12.675,13.375,13.925,14.375,14.975,15.375
2018-01-05,10.475,11.725,12.575,13.275,13.825,14.250,14.825,15.225
...,...,...,...,...,...,...,...,...
2020-11-18,22.410,24.875,26.175,26.225,26.125,26.125,26.175,26.275
2020-11-19,24.475,25.925,26.075,25.925,25.975,25.975,25.925,26.200
2020-11-20,24.375,25.825,25.975,25.925,26.025,26.075,26.100,26.150
2020-11-23,24.100,25.725,25.875,25.725,25.825,25.875,25.850,26.000
2020-11-24,23.510,25.270,25.590,25.550,25.600,25.690,25.700,26.000

In [47]:
df3=pd.read_excel("Term Structure of VIX-2.xlsx","VIXSPOT")

In [50]:
df3=df3.set_index(['Dates'])

In [55]:
reg1=pd.concat([df2,df3['Close']],axis=1,join='inner')

In [62]:
reg1['change1']=reg1['UX1 Index']-reg1['Close']
reg1['change2']=reg1['UX2 Index']-reg1['Close']
reg1['change3']=reg1['UX3 Index']-reg1['Close']
reg1['change4']=reg1['UX4 Index']-reg1['Close']
reg1['change5']=reg1['UX5 Index']-reg1['Close']
reg1['change6']=reg1['UX6 Index']-reg1['Close']
reg1['change7']=reg1['UX7 Index']-reg1['Close']
reg1['change8']=reg1['UX8 Index']-reg1['Close']

In [64]:
reg1.to_excel('reg1.xlsx')

In [66]:
regfin=pd.read_excel('reg12.xlsx','Sheet1')

In [67]:
regfin

,Dates,UX1 Index,UX2 Index,UX3 Index,UX4 Index,UX5 Index,UX6 Index,UX7 Index,UX8 Index,UX1 T,...,Close,Close T,change1,change2,change3,change4,change5,change6,change7,change8
0,2018-01-02,10.875,11.975,12.825,13.525,14.025,14.525,15.125,15.575,11.95,...,9.77,11.91,1.105,2.205,2.205,2.205,2.205,2.205,2.205,2.205
1,2018-01-03,10.675,11.825,12.625,13.325,13.825,14.325,14.925,15.350,11.95,...,9.15,11.91,1.525,2.675,2.675,2.675,2.675,2.675,2.675,2.675
2,2018-01-04,10.575,11.825,12.675,13.375,13.925,14.375,14.975,15.375,11.95,...,9.22,11.91,1.355,2.605,2.605,2.605,2.605,2.605,2.605,2.605
3,2018-01-05,10.475,11.725,12.575,13.275,13.825,14.250,14.825,15.225,11.95,...,9.22,11.91,1.255,2.505,2.505,2.505,2.505,2.505,2.505,2.505
4,2018-01-08,10.475,11.675,12.475,13.225,13.775,14.225,14.825,15.200,11.95,...,9.52,11.91,0.955,2.155,2.155,2.155,2.155,2.155,2.155,2.155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722,2020-11-12,25.875,26.575,26.675,26.275,26.075,26.125,26.075,25.850,22.41,...,25.35,23.84,0.525,1.225,1.225,1.225,1.225,1.225,1.225,1.225
723,2020-11-13,23.325,25.075,25.725,25.675,25.525,25.525,25.425,25.325,22.41,...,23.10,23.84,0.225,1.975,1.975,1.975,1.975,1.975,1.975,1.975
724,2020-11-16,22.925,24.525,25.525,25.575,25.525,25.650,25.675,25.525,22.41,...,22.45,23.84,0.475,2.075,2.075,2.075,2.075,2.075,2.075,2.075
725,2020-11-17,22.975,24.025,25.225,25.375,25.375,25.425,25.425,25.525,22.41,...,22.71,23.84,0.265,1.315,1.315,1.315,1.315,1.315,1.315,1.315
726,2020-11-18,22.410,24.875,26.175,26.225,26.125,26.125,26.175,26.275,22.41,...,23.84,23.84,-1.430,1.035,1.035,1.035,1.035,1.035,1.035,1.035

In [101]:
regfin['SpotChange']=regfin['Close T']-regfin['Close']
regfin['futchange1']=regfin['UX1 T']-regfin['UX1 Index']
regfin['futchange2']=regfin['UX2 T']-regfin['UX2 Index']
regfin['futchange3']=regfin['UX3 T']-regfin['UX3 Index']
regfin['futchange4']=regfin['UX4 T']-regfin['UX4 Index']
regfin['futchange5']=regfin['UX5 T']-regfin['UX5 Index']
regfin['futchange6']=regfin['UX6 T']-regfin['UX6 Index']
regfin['futchange7']=regfin['UX7 T']-regfin['UX7 Index']
regfin['futchange8']=regfin['UX7 T']-regfin['UX8 Index']


regfin['change1']=regfin['UX1 Index']-regfin['Close']
regfin['change2']=regfin['UX2 Index']-regfin['Close']
regfin['change3']=regfin['UX3 Index']-regfin['Close']
regfin['change4']=regfin['UX4 Index']-regfin['Close']
regfin['change5']=regfin['UX5 Index']-regfin['Close']
regfin['change6']=regfin['UX6 Index']-regfin['Close']
regfin['change7']=regfin['UX7 Index']-regfin['Close']
regfin['change8']=regfin['UX8 Index']-regfin['Close']

0      5.355
1      5.775
2      5.755
3      5.605
4      5.305
       ...
722    0.725
723    2.325
724    3.225
725    2.715
726    2.335
Name: change7, Length: 727, dtype: float64

## 1st Table

In [145]:
list2=['change1','change2','change3','change4','change5','change6','change7','change8']
intercept=[]
tstat=[]
r=[]
for nam in list2:
    model=sm.OLS(regfin['SpotChange'],sm.add_constant(regfin[nam]))
    intercept.append(model.fit().params[1])
    tstat.append(model.fit().tvalues[1])
    r.append(model.fit().rsquared_adj)

In [146]:
intercept
tstat
r

[-0.0004996840773292544,
 0.002311712068660876,
 0.003029523285614011,
 0.006680872875354127,
 0.011892315994588398,
 0.012091591859782702,
 0.012683393193186343,
 0.027702685739636412]

In [147]:
table1=pd.DataFrame(index=['UX1','UX2','UX3','UX4','UX5','UX6','UX7','UX8'],columns=['beta1','tstat','r'])

In [148]:
table1['beta1']=intercept
table1['tstat']=tstat
table1['r']=r
table1=table1.T
table1.style.set_caption("Spot vix on basis : ST âˆ’St = Î±1+Î²1Â·(Ft,T âˆ’St)+ Îµ1,t")

## 2nd Table

In [150]:
list2=['change1','change2','change3','change4','change5','change6','change7','change8']
list3=['futchange1','futchange2','futchange3','futchange4','futchange5','futchange6','futchange7','futchange8']

intercept=[]
tstat=[]
r=[]
for nim,nam in list(zip(list3,list2)):
    model=sm.OLS(regfin[nim],sm.add_constant(regfin[nam]))
    intercept.append(model.fit().params[1])
    tstat.append(model.fit().tvalues[1])
    r.append(model.fit().rsquared_adj)

In [151]:
table1=pd.DataFrame(index=['UX1','UX2','UX3','UX4','UX5','UX6','UX7','UX8'],columns=['beta1','tstat','r'])

In [152]:
table1['beta1']=intercept
table1['tstat']=tstat
table1['r']=r
table1=table1.T
table1.style.set_caption("VIX Futures on basis: ST âˆ’St = Î±1+Î²1Â·(Ft,T âˆ’St)+ Îµ1,t")